# Generated by Django 3.2.7 on 2021-10-03 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=100)),
                ('num_floors', models.IntegerField()),
                ('num_apartments', models.IntegerField()),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='societies.society')),
            ],
        ),
    ]
